<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="QuestPDF" Version="2026.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PeopleCore.Application\PeopleCore.Application.csproj" />
  </ItemGroup>

</Project>
