<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PeopleCore.Domain\PeopleCore.Domain.csproj" />
    <ProjectReference Include="$(M2NetCoreProject)" Condition=" '$(M2NetCoreProject)' != '' " />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UsesM2NetCore>true</UsesM2NetCore>
  </PropertyGroup>

</Project>
